name: github pages

on:
  push:
    branches:
      - main  # Set a branch that will trigger a deployment
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive  # Fetch Hugo themes (true OR recursive) and CV
          token: ${{ secrets.GH_CV_PAT }}  # authenticate access to CV
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Pandoc
        uses: pandoc/actions/setup@v1

      - name: Generate CV _index.md
        id: generate_cv
        run: |
          pip install -r requirements.txt
          bash ${GITHUB_WORKSPACE}/content/cv/csl/update_csl.sh
          python ${GITHUB_WORKSPACE}/content/cv/generate_cv.py

      - name: Generate CV PDF
        uses: xu-cheng/texlive-action@v2
        with:
            run: |
                cd ${GITHUB_WORKSPACE}/content/cv/cv
                latexmk -quiet -pdf main.tex
                cp main.pdf ${GITHUB_WORKSPACE}/uploads/cv.pdf
                cd ${GITHUB_WORKSPACE}

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
