name: github pages

on:
  push:
    branches:
      - main  # Set a branch that will trigger a deployment
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Generate CV
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: |
          pip install -r requirements.txt
          cd ${GITHUB_WORKSPACE}/content/cv
          python generate_cv.py
          pwd
          ls ..
          ls ../cv
      - uses: docker://pandoc/latex
        with:
            args: >-
                ${GITHUB_WORKSPACE}/content/cv/_index.md
                --variable
                geometry=margin=0.5in
                --variable
                pagestyle=empty
                -o
                ${GITHUB_WORKSPACE}/static/uploads/cv.pdf
                --pdf-engine
                xelatex
    
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
